# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: 321bca5d
    url: /
    weight: 10
  - name: Papers
    identifier: 8c0dde1b
    url: /#papers
    weight: 20
  - name: Talks
    identifier: c27f45a0
    url: /#talks
    weight: 30
  - name: Experience
    identifier: aa587d19
    url: experience/
    weight: 40
  - name: Blog
    identifier: posts
    url: /blog/
    weight: 50
